name: 'Setup Rye MultiOS'
description: 'Set up Rye environment on Linux, macOS, and Windows'
outputs:
  status:
    description: 'Status of the setup'
runs:
  using: 'composite'
  steps:
    - name: Install Rye on Linux and macOS
      run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
      shell: bash
      if: runner.os != 'Windows'
    - name: Add Rye to PATH
      run: |
        echo $HOME
        echo "echo "$HOME/.rye/env" >> $GITHUB_PATH
      shell: bash
    - name: Verify Rye Installation
      run: rye --version
      shell: bash
    - name: Set output
      run: echo "status=success" >> $GITHUB_ENV
      shell: bash
