name: 'Setup Rye MultiOS'
description: 'Set up Rye environment on Linux, macOS, and Windows'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.8'
outputs:
  status:
    description: 'Status of the setup'
runs:
  using: 'composite'
  steps:
    - name: Install Rye on Linux and macOS
      run: curl -sSf https://rye-up.com/get | bash
      shell: bash
      if: runner.os != 'Windows'
    - name: Install Rust and Rye on Windows
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        cargo install --git https://github.com/mitsuhiko/rye rye
      shell: bash
      if: runner.os == 'Windows'
    - name: Verify Rye Installation
      run: rye --version
      shell: bash
    - name: Pin Python Version
      run: rye pin ${{ inputs.python-version }}
      shell: bash
    - name: Set output
      run: echo "status=success" >> $GITHUB_ENV
      shell: bash
