name: 'Setup Rye MultiOS'
description: 'Set up Rye environment on Linux, macOS, and Windows'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.8'
outputs:
  status:
    description: 'Status of the setup'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      run: git clone https://github.com/${{ github.repository }}.git ${{ github.action_path }}
      shell: bash
    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      shell: bash
    - name: Install Rye
      run: cargo install --git https://github.com/mitsuhiko/rye rye
      shell: bash
    - name: Verify Rye Installation
      run: rye --version
      shell: bash
    - name: Pin Python Version
      run: rye pin ${{ inputs.python-version }}
      shell: bash
    - name: Sync Rye Environment
      run: rye sync
      shell: bash
    - name: Set output
      run: echo "status=success" >> $GITHUB_ENV
      shell: bash
