name: 'Setup Rye MultiOS'
description: 'Set up Rye environment on Linux, macOS, and Windows'
outputs:
  status:
    description: 'Status of the setup'
runs:
  using: 'composite'
  steps:
    - name: Install Rye on Linux and macOS
      run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
      shell: bash
      if: runner.os != 'Windows'
    - name: Install Rust and Rye on Windows
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        cargo install --git https://github.com/mitsuhiko/rye rye
      shell: bash
      if: runner.os == 'Windows'
    - name: Add Rye to PATH
      run: |
        echo "$HOME/.rye/env" >> $GITHUB_PATH
        echo "$HOME/.rye/shims" >> $GITHUB_PATH
      shell: bash
    - name: Verify Rye Installation
      run: rye --version
      shell: bash
    - name: Set output
      run: echo "status=success" >> $GITHUB_ENV
      shell: bash
branding:
  icon: 'check-circle'
  color: 'white'
