name: Test Setup Rye MultiOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use setup-rye-multiOS action
      uses: ./
    - name: Verify Rye Installation
      run: |
        rye init my-project
        cd my-project
        rye pin 3.8
        rye sync
        python --version
        
